ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_BATTERY_BQ27541_OPPO)		+= bq27541_fuelgauger.o
obj-$(CONFIG_HMAC_SHA1_BQ27541_OPPO)	+= hmac_sha1_bq27541.o
obj-$(CONFIG_QPNP_CHARGER_OPPO)			+= qpnp-charger.o
obj-$(CONFIG_BQ24196_CHARGER_OPPO)		+= bq24196-charger.o
obj-$(CONFIG_PIC1503_FASTCG_OPPO)		+= pic16F1503_fastcg.o
obj-$(CONFIG_BATTERY_BQ27541_ONYX)		+= bq27541_fuelgauger_onyx.o
obj-$(CONFIG_HMAC_SHA1_BQ27541_ONYX)	+= hmac_sha1_bq27541_onyx.o
obj-$(CONFIG_QPNP_CHARGER_ONYX)			+= qpnp-charger_onyx.o
obj-$(CONFIG_BQ24196_CHARGER_ONYX)		+= bq24196-charger_onyx.o
